Repository libsv/payd, pull requests merged in 2021-09, with the labels that each got.

#10 Rename headersv -> headersclient
  cmd/bip270-server/main.go
  config/config.go
  config/viper.go
  data/http/headersv.go
Labels: bug

#14 Remove PPTCL from PayD
  .goreleaser.yml
  broadcast.go
  cmd/rest-server/main.go
  cmd/web-app/html/header.html
  cmd/web-app/html/index.html
  cmd/web-app/html/test.html
  cmd/web-app/main.go
  cmd/web-app/static/css/app.css
  cmd/web-app/static/css/simple-grid.min.css
  cmd/web-app/static/js/app.js
  cmd/web-app/static/js/qrcode.min.js
  data/mapi/mapi.go
  data/paymail/models/outputs.go
  data/paymail/paymail.go
  go.mod
  paymail.go
  ppctl_merchant.go
  ppctl_output.go
  ppctl_payment.go
  ppctl_payment_request.go
  ppctl_payment_test.go
  ppctl_tx_status.go
  service/ppctl/README.md
  service/ppctl/payment.go
  service/ppctl/payment_mapi.go
  service/ppctl/paymentrequest.go
  service/ppctl/paymentrequest_mapi.go
  service/ppctl/paymentrequest_paymail.go
  service/ppctl/txstatus.go
  transports/http/bip270_payment.go
  transports/http/bip270_payment_request.go
  transports/http/request.go
  transports/http/txstatus.go
  vendor/github.com/libsv/go-bc/spv/createenvelope.go
  vendor/github.com/libsv/go-bc/spv/creator.go
  vendor/github.com/libsv/go-bc/spv/envelope.go
  vendor/github.com/libsv/go-bc/spv/errors.go
  vendor/github.com/libsv/go-bc/spv/verifier.go
  vendor/github.com/libsv/go-bc/spv/verifymerkleproof.go
  vendor/github.com/libsv/go-bc/spv/verifypayment.go
  vendor/github.com/matryer/is/.gitignore
  vendor/github.com/matryer/is/.travis.yml
  vendor/github.com/matryer/is/LICENSE
  vendor/github.com/matryer/is/README.md
  vendor/github.com/matryer/is/go.mod
  vendor/github.com/matryer/is/is-1.7.go
  vendor/github.com/matryer/is/is-before-1.7.go
  vendor/github.com/matryer/is/is.go
  vendor/modules.txt
Labels: feature

#15 Feat/invoice endpoint
  cmd/rest-server/main.go
  data/noop/invoice.go
  data/sqlite/invoice.go
  data/sqlite/migrations/1_initial.up.sql
  docs/docs.go
  go.mod
  invoice.go
  invoices.go
  service/invoice.go
  transports/http/balance.go
  transports/http/invoices.go
  transports/http/proofs.go
  transports/http/routes.go
  vendor/modules.txt
Labels: feature

#16 Create Destinations
  cmd/rest-server/main.go
  config/viper.go
  data/noop/invoice.go
  data/paymail/paymail.go
  data/sqlite/derivation_paths.go
  data/sqlite/destinations.go
  data/sqlite/invoice.go
  data/sqlite/migrations/1_initial.up.sql
  derivation_path.go
  destinations.go
  docker-compose.yml
  docs/docs.go
  invoices.go
  payd.go
  service/destinations.go
  service/invoice.go
  transports/http/invoices.go
  transports/http/proofs.go
Labels: feature

#17 adding get endpoint for destinations
  cmd/rest-server/main.go
  data/sqlite/destinations.go
  destinations.go
  payd.go
  service/destinations.go
  transports/http/destinations.go
  transports/http/invoices.go
  transports/http/routes.go
Labels: feature

#18 Fix: Docker build and run issues
  .gitignore
  Dockerfile
  Makefile
  docker-compose.yml
Labels: bug

#19 Feat: /owner
  Makefile
  cmd/rest-server/main.go
  data/sqlite/migrations/1_initial.up.sql
  data/sqlite/owner.go
  go.sum
  owners.go
  service/owners.go
  transports/http/balance.go
  transports/http/owners.go
  transports/http/routes.go
Labels: feature

#26 Updating Owners domain
  data/sqlite/migrations/1_initial.up.sql
  data/sqlite/owner.go
  go.sum
  service/owners.go
  transports/http/owners.go
  users.go
Labels: enhancement

#27 renaming of root package from gopayd to payd
  .github/workflows/go.yml
  balance.go
  broadcast.go
  data/noop/invoice.go
  data/paymail/paymail.go
  data/sqlite/balance.go
  data/sqlite/derivation_paths.go
  data/sqlite/destinations.go
  data/sqlite/invoice.go
  data/sqlite/owner.go
  data/sqlite/private_keys.go
  data/sqlite/proof_callbacks.go
  data/sqlite/proofs.go
  data/sqlite/transaction.go
  derivation_path.go
  destinations.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  fees.go
  invoices.go
  mocks/proofs_writer.go
  payd.go
  paymail.go
  payments.go
  private_key.go
  proofs.go
  service/balance.go
  service/destinations.go
  service/invoice.go
  service/owners.go
  service/payments.go
  service/private_keys.go
  service/proofs.go
  service/proofs_test.go
  transaction.go
  transports/http/balance.go
  transports/http/destinations.go
  transports/http/invoices.go
  transports/http/owners.go
  transports/http/payments.go
  transports/http/proofs.go
  txo.go
  users.go
Labels: bug

#28 Fix: SQL err for proofs
  data/sqlite/proofs.go
Labels: bug

#29 rename gopayd payd
  .golangci.yml
  Makefile
  cmd/rest-server/main.go
  config/config.go
  config/databases/databases.go
  data/http/headersv.go
  data/http/interfaces.go
  data/sqlite/proof_callbacks.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  transports/http/balance.go
  transports/http/destinations.go
  transports/http/invoices.go
  transports/http/owners.go
  transports/http/payments.go
  transports/http/proofs.go
  vendor/github.com/alecthomas/template/LICENSE
  vendor/github.com/alecthomas/template/README.md
  vendor/github.com/alecthomas/template/doc.go
  vendor/github.com/alecthomas/template/exec.go
  vendor/github.com/alecthomas/template/funcs.go
  vendor/github.com/alecthomas/template/go.mod
  vendor/github.com/alecthomas/template/helper.go
  vendor/github.com/alecthomas/template/parse/lex.go
  vendor/github.com/alecthomas/template/parse/node.go
  vendor/github.com/alecthomas/template/parse/parse.go
  vendor/github.com/alecthomas/template/template.go
  vendor/modules.txt
Labels: bug

#30 fixing balance endpoint as db model changed
  data/sqlite/balance.go
Labels: bug

#35 Fix: Generate master key on init
  cmd/rest-server/main.go
  data/sqlite/migrations/1_initial.up.sql
  data/sqlite/private_keys.go
Labels: feature

#40 removing v prefix for docker image
  .goreleaser.yml
Labels: bug

#36 Feature: Pay endpoint
  Makefile
  cmd/rest-server/main.go
  config/config.go
  config/defaults.go
  config/viper.go
  data/http/interfaces.go
  data/http/p4.go
  data/sqlite/balance.go
  data/sqlite/migrations/1_initial.up.sql
  data/sqlite/proofs.go
  data/sqlite/transaction.go
  data/sqlite/utxo.go
  docker-compose.yml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  pay.go
  payments.go
  service/pay.go
  transports/http/balance.go
  transports/http/invoices.go
  transports/http/owners.go
  transports/http/pay.go
  transports/http/payments.go
  transports/http/routes.go
  txo.go
  vendor/github.com/alecthomas/template/LICENSE
  vendor/github.com/alecthomas/template/README.md
  vendor/github.com/alecthomas/template/doc.go
  vendor/github.com/alecthomas/template/exec.go
  vendor/github.com/alecthomas/template/funcs.go
  vendor/github.com/alecthomas/template/helper.go
  vendor/github.com/alecthomas/template/parse/lex.go
  vendor/github.com/alecthomas/template/parse/node.go
  vendor/github.com/alecthomas/template/parse/parse.go
  vendor/github.com/alecthomas/template/template.go
  vendor/modules.txt
Labels: feature

#42 Fix: Docker volume mount
  Dockerfile
Labels: bug

#43 Fix: Go releaser fix
  Dockerfile.releaser
Labels: bug

#39 Feature/send pay
  cli/data/http/send.go
  cli/models/pay.go
  cli/payment.go
  cli/send.go
  cli/service/pay.go
Labels: feature

#46 Debug Middleware
  cmd/rest-server/main.go
  docker-compose.yml
  transports/http/middleware/debug_logger.go
Labels: enhancement

#50 Fix: Raw SQL error
  data/sqlite/transaction.go
Labels: bug

#51 Enhancement: Better docker container layers
  Dockerfile.releaser
Labels: enhancement
